// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbLOnHRILTg-KS2KF7xz0rSL699Xkv_ng',
    appId: '1:783614905355:web:121e598bf66bfb0c534b0e',
    messagingSenderId: '783614905355',
    projectId: 'rfid-user-db713',
    authDomain: 'rfid-user-db713.firebaseapp.com',
    databaseURL: 'https://rfid-user-db713-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-user-db713.firebasestorage.app',
    measurementId: 'G-8CGX1K5506',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClzvn2T6htHQ6SPWl1L2v2GhsF2snDlBE',
    appId: '1:783614905355:android:69c217d4500c9840534b0e',
    messagingSenderId: '783614905355',
    projectId: 'rfid-user-db713',
    databaseURL: 'https://rfid-user-db713-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-user-db713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnAQiqOhaW_vvHgHLePNW9Dq3actmGqi0',
    appId: '1:783614905355:ios:ac56074bd0f9ab50534b0e',
    messagingSenderId: '783614905355',
    projectId: 'rfid-user-db713',
    databaseURL: 'https://rfid-user-db713-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-user-db713.firebasestorage.app',
    iosClientId: '783614905355-cf56gsgh0uqcbd75a8gdbckgipv4nueq.apps.googleusercontent.com',
    iosBundleId: 'com.example.userRfid',
  );
}
